# Generated by Django 2.0.2 on 2018-07-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imagen',
            field=models.ImageField(upload_to='nodos', verbose_name='portada del libro'),
        ),
    ]
