# Generated by Django 2.0.2 on 2018-07-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0003_auto_20180709_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='usaurio',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='book',
            name='imagen',
            field=models.ImageField(upload_to='nodos', verbose_name='portada del libro'),
        ),
    ]
