# Generated by Django 2.0.2 on 2018-07-19 18:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0004_auto_20180709_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Escribe aquí una breve descripción del libro'),
        ),
    ]
