# Generated by Django 2.0.2 on 2018-07-19 19:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0005_auto_20180719_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='procedencia',
            field=ckeditor.fields.RichTextField(max_length=200, null=True, verbose_name='Procendencia'),
        ),
        migrations.AlterField(
            model_name='book',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
