# Generated by Django 2.0.2 on 2018-07-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0006_auto_20180719_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias de estudio'},
        ),
        migrations.AddField(
            model_name='category',
            name='cat_estudio',
            field=models.CharField(choices=[('PROD', 'Período'), ('LU', 'Lugar'), ('PRSO', 'Personajes'), ('INS', 'Instituciones')], default='PROD', max_length=2),
        ),
    ]
