# Generated by Django 2.0.2 on 2018-07-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0010_auto_20180723_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categorias_estudio',
        ),
        migrations.AddField(
            model_name='book',
            name='categorias_estudio',
            field=models.ManyToManyField(related_name='get_nodos', to='nodos.CategoryStudy', verbose_name='Categorias de estudio'),
        ),
    ]
