# Generated by Django 2.0.2 on 2018-07-27 00:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0013_auto_20180724_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Escribe aquí una breve descripción del libro'),
        ),
    ]
