# Generated by Django 2.0.2 on 2018-08-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0014_auto_20180726_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_estudio',
            field=models.CharField(choices=[('01', 'Período'), ('02', 'Lugar'), ('03', 'Personajes'), ('04', 'Proyectos'), ('05', 'Instituciones'), ('06', 'Conceptos/Ideas'), ('07', 'Diciplinas'), ('08', 'Acontecimientos'), ('09', 'Estilos/Corrientes'), ('10', 'Materiales/Tecnologías'), ('11', 'Ausencias'), ('12', 'Palabras Oscuras')], default='01', max_length=2, verbose_name='Categorias de estudio'),
        ),
    ]
