# Generated by Django 2.0.2 on 2018-08-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0015_auto_20180801_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_estudio', models.CharField(max_length=200, verbose_name='Nueva categoria de estudio')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de estudio',
                'verbose_name_plural': 'Categorias de estudio',
                'ordering': ['created'],
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categorias',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_estudio',
        ),
        migrations.AddField(
            model_name='category',
            name='categorias_estudio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nodos.CategoryStudy', verbose_name='Categorias de estudio'),
        ),
    ]
