# Generated by Django 2.0.2 on 2018-08-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0016_auto_20180802_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categorias_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodos.CategoryStudy', verbose_name='Categorias de estudio'),
        ),
    ]
