# Generated by Django 2.0.2 on 2018-08-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0018_remove_category_categorias_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
