# Generated by Django 2.0.2 on 2018-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0019_auto_20180802_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_estudio', models.CharField(choices=[('01', 'Período'), ('02', 'Lugar'), ('03', 'Personajes'), ('04', 'Proyectos'), ('05', 'Instituciones'), ('06', 'Conceptos/Ideas'), ('07', 'Diciplinas'), ('08', 'Acontecimientos'), ('09', 'Estilos/Corrientes'), ('10', 'Materiales/Tecnologías'), ('11', 'Ausencias'), ('12', 'Palabras Oscuras')], default='01', max_length=2, verbose_name='Categorias de estudio')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='CategoryStudy',
        ),
        migrations.AddField(
            model_name='book',
            name='categorias',
            field=models.ManyToManyField(related_name='get_nodos', to='nodos.Category', verbose_name='Relaciones'),
        ),
    ]
