# Generated by Django 2.0.2 on 2018-08-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0020_auto_20180802_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_estudio', models.CharField(max_length=200, verbose_name='Nueva Categoria de estudio')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de estudio',
                'verbose_name_plural': 'Categorias de estudio',
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodos.CategoryStudy'),
        ),
    ]
