# Generated by Django 2.0.2 on 2018-08-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0021_auto_20180802_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriasEstudio', to='nodos.CategoryStudy', verbose_name='Categorias de estudio'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='nodos.Category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='categorystudy',
            name='categoria_estudio',
            field=models.CharField(max_length=200, verbose_name='Categoria de estudio'),
        ),
    ]
