# Generated by Django 2.0.2 on 2018-08-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0022_auto_20180807_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, null='True', verbose_name='Categoria'),
        ),
    ]
