# Generated by Django 2.0.2 on 2018-08-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0023_auto_20180808_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catest',
            field=models.ManyToManyField(blank=True, related_name='_category_catest_+', to='nodos.Category', verbose_name='Revisa categorias'),
        ),
        migrations.AddField(
            model_name='category',
            name='for_inline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models_rf', to='nodos.Category'),
        ),
    ]
