# Generated by Django 2.0.2 on 2018-08-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0024_auto_20180815_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Título')),
            ],
        ),
    ]
