# Generated by Django 2.0.2 on 2018-08-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0025_tmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created'], 'verbose_name': 'Palabra clave', 'verbose_name_plural': 'Palabras Claves'},
        ),
    ]
