# Generated by Django 2.0.2 on 2018-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0026_auto_20180827_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lat',
            field=models.FloatField(blank=True, help_text='latitud <a href="https://www.bufa.es/google-maps-latitud-longitud/">ISBN number</a>', max_length=13, null=True, verbose_name='Introduce la latitud'),
        ),
        migrations.AddField(
            model_name='book',
            name='long',
            field=models.FloatField(blank=True, help_text='longitud <a href="https://www.bufa.es/google-maps-latitud-longitud/">ISBN number</a>', max_length=13, null=True, verbose_name='Introduce la longitud'),
        ),
        migrations.AddField(
            model_name='book',
            name='mapHeight',
            field=models.FloatField(default='15', help_text='Entre 15 - 65', max_length=2, verbose_name='Introduce el ancho del marcador (círculo), en el mapa'),
        ),
        migrations.AddField(
            model_name='book',
            name='mapWidth',
            field=models.FloatField(default='15', help_text='Entre 15 - 65', max_length=2, verbose_name='Introduce el ancho del marcador (círculo), en el mapa'),
        ),
        migrations.AddField(
            model_name='book',
            name='pais',
            field=models.CharField(default='México', max_length=20, verbose_name='País o Edo'),
        ),
    ]
