# Generated by Django 2.0.2 on 2018-10-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0027_auto_20181005_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Escribe aquí una breve descripción del libro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lat',
            field=models.FloatField(blank=True, help_text='latitud <a href="https://www.bufa.es/google-maps-latitud-longitud/">Obtener latitud</a>', max_length=13, null=True, verbose_name='Introduce la latitud'),
        ),
        migrations.AlterField(
            model_name='book',
            name='long',
            field=models.FloatField(blank=True, help_text='longitud <a href="https://www.bufa.es/google-maps-latitud-longitud/">Obteber longitud</a>', max_length=13, null=True, verbose_name='Introduce la longitud'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pais',
            field=models.CharField(default='México', max_length=20, verbose_name='País y/o Edo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='procedencia',
            field=models.TextField(max_length=200, null=True, verbose_name='Procendencia'),
        ),
        migrations.AlterField(
            model_name='book',
            name='resumen',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
