# Generated by Django 2.0.2 on 2018-10-11 20:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0028_auto_20181011_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Escribe aquí una breve descripción del libro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='procedencia',
            field=ckeditor.fields.RichTextField(max_length=200, null=True, verbose_name='Procendencia'),
        ),
        migrations.AlterField(
            model_name='book',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
