# Generated by Django 2.0.2 on 2018-11-06 05:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0032_auto_20181013_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Escribe aquí una breve descripción del libro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='periodo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('00', '1900'), ('10', '1910'), ('20', '1920'), ('30', '1930'), ('40', '1940'), ('50', '1950'), ('60', '1960'), ('70', '1970'), ('80', '1980'), ('90', '1990'), ('2m', '2000'), ('21', '2010'), ('22', '2020')], default='00', help_text='Seleccione las décadas que abarca el libro.', max_length=60, verbose_name='Periódo de tiempo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='procedencia',
            field=models.TextField(max_length=200, null=True, verbose_name='Procendencia'),
        ),
    ]
