# Generated by Django 2.0.2 on 2018-11-07 19:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0034_book_cate_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Escribe aquí una breve descripción del libro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='procedencia',
            field=ckeditor.fields.RichTextField(max_length=200, null=True, verbose_name='Procendencia'),
        ),
    ]
