# Generated by Django 2.0.2 on 2018-11-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0035_auto_20181107_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cate_estudio',
        ),
        migrations.AddField(
            model_name='book',
            name='cate_estudio',
            field=models.ManyToManyField(help_text='Seleccione las categorías de estudio que contine el libro.', related_name='get_cat_estudy', to='nodos.CategoryStudy', verbose_name='Categorías de estudio'),
        ),
    ]
