# Generated by Django 2.0.2 on 2018-11-09 02:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0036_auto_20181107_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=8000, verbose_name='Escribe aquí una breve descripción del libro'),
        ),
    ]
