# Generated by Django 2.0.2 on 2018-07-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('puesto', models.CharField(max_length=200, null=True, verbose_name='Puesto')),
                ('descripcion', models.TextField(verbose_name='Escribe aquí una breve descripción del libro')),
                ('imagen', models.ImageField(upload_to='about', verbose_name='Fotografía')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link red social')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['created'],
            },
        ),
    ]
